### ISSUE TITLE
Multiagent training

### ISSUE THREAD

**Issue by sAz-G** [utiasDSL/gym-pybullet-drones#171]
Hi everyone,

My goal is to create collision avoidance training environment with multiple drones (and obstacles).

Is there an example for training custom Multiagent environments in the main branch using stablebaseline3? Is there an example for using the given environments (for example FlockAviary)?

I could find only examples in the master branch using rllib ([multiagent](experiments/learning/multiagent.py))

**Comment by JacopoPan** [comment]
Hello @sAz-G 

I apologize but, since bringing the repo to `gymnasium` and `stable-baselines3` 2.0, I haven't yet had the time to create multi-agent examples for the latter.

We are still focusing on the development of software-in-the-loop interfaces for `crazyflie-firmware` and `betaflight`.
As soon as those are complete, we will add more learning examples.
