### ISSUE TITLE
check_env fails in `examples/learning.py`: The observation returned by the `reset()` method does not match the given observation space

### ISSUE THREAD

**Issue by vkotaru** [utiasDSL/gym-pybullet-drones#87]
`examples/learning.py` fails with 
```
The observation returned by the `reset()` method does not match the given observation space, 
```

Best
-Prasanth

**Comment by JacopoPan** [comment]
Hi @vkotaru,

thank you for noting this, I checked and it comes from this line in `gym`
https://github.com/openai/gym/blob/master/gym/spaces/box.py#L188
because the NumPy observation was promoted to `float64` (and the space is declared as `float32`)

For now I'm patching it with a cast `.astype('float32')` in `BaseSingleAgentAviary (and think if or how it could be done differently).
